services:
  - type: web
    name: telegram-vote-bot
    env: python
    plan: free
    runtime: python
    pythonVersion: 3.10.12
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
