services:
  - type: web
    name: telegram_vote_bot
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
